In [88]:
import numpy as np
import pandas as pd

import os
import numpy as np
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import plotly as py
import plotly.graph_objs as go
from nltk.stem import PorterStemmer
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import operator 
import pandas as pd
import string
import re
import numpy as np
import sys
import os
import requests
import nltk
import pickle


init_notebook_mode(connected=True) #do not miss this line

from gensim import corpora, models, similarities

import warnings
warnings.filterwarnings("ignore")

In [85]:
main = pd.read_csv('training.1600000.processed.noemoticon.csv', header=0, encoding='latin-1', usecols=[0,5], names=['polarity','tweet'])

In [86]:
main.describe()

           polarity
count  1.599999e+06
mean   2.000001e+00
std    2.000001e+00
min    0.000000e+00
25%    0.000000e+00
50%    4.000000e+00
75%    4.000000e+00
max    4.000000e+00

In [78]:
df = pd.read_csv('training.1600000.processed.noemoticon.csv', header=0, encoding='latin-1', usecols=[0,5], names=['polarity','tweet'])

In [79]:
df = df[df.polarity == 0]

In [80]:
classArray = []

count = 799999
while count:
    classArray.append('2')
    count -= 1

In [82]:
df['class'] = classArray

In [83]:
df.describe()

       polarity
count  799999.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0

In [89]:
def strip_links(text):
    link_regex    = re.compile('((https?):((//)|(\\\\))+([\w\d:#@%/;$()~_?\+-=\\\.&](#!)?)*)', re.DOTALL)
    links         = re.findall(link_regex, text)
    for link in links:
        text = text.replace(link[0], ', ')
    
    return text

def strip_all_entities(text):
    """
    Remove twitter handles and hashtags
    """
    
    entity_prefixes = ['_', '@','#']
    for separator in string.punctuation:
        if separator not in entity_prefixes :
            text = text.replace(separator,' ')
    words = []
    for word in text.split():
        word = word.strip()
        if word:
            if word[0] not in entity_prefixes:
                words.append(word)

    return ' '.join(words)


def remove_stop_words(text):
    
    punctuation = set(string.punctuation)
    numbers = set(string.digits)
    stop_words = set(stopwords.words('english') + ['amp', 'via', 'https', 'Retweet', 'retweet', 'retweets', 'Retweets', 'RT']) 
    words = []
    for word in text.split():
        if word not in (stop_words or punctuation or numbers):
            words.append(word.lower())
            
    return ' '.join(words)

def remove_numbers(text):
    words = []
    for word in text.split():
        if word.isalpha() == True:
            words.append(word)
        else:
            continue
    
    return ' '.join(words)



df['tweet'] = df['tweet'].apply(strip_links)
df['tweet'] = df['tweet'].apply(strip_all_entities)
df['tweet'] = df['tweet'].apply(strip_emojis)
df['tweet'] = df['tweet'].apply(remove_stop_words)
df['tweet'] = df['tweet'].apply(remove_numbers)

In [90]:
df.head()

   polarity                                              tweet class
0         0  upset update facebook texting might cry result...     2
1         0  i dived many times ball managed save the rest ...     2
2         0                   whole body feels itchy like fire     2
3         0                                 behaving mad i see     2
4         0                                         whole crew     2

In [91]:
df.drop(columns=['polarity'])

                                                    tweet class
0       upset update facebook texting might cry result...     2
1       i dived many times ball managed save the rest ...     2
2                        whole body feels itchy like fire     2
3                                      behaving mad i see     2
4                                              whole crew     2
5                                                need hug     2
6       hey long time see yes rains bit bit lol i fine...     2
7                                                    nope     2
8                                               que muera     2
9                         spring break plain city snowing     2
10                                         i pierced ears     2
11        i bear watch and i thought ua loss embarrassing     2
12              it counts idk i either never talk anymore     2
13      would first gun really though zac snyder douch...     2
14                     i wish i got watch i miss premiere     2
15      hollis death scene hurt severely watch film wr...     2
16                                             file taxes     2
17         ahh ive always wanted see rent love soundtrack     2
18           oh dear were drinking forgotten table drinks     2
19                                      day get much done     2
20      one friend called asked meet mid valley today ...     2
21                                    i baked cake i ated     2
22                                       week going hoped     2
23                                   blagh class tomorrow     2
24                              i hate i call wake people     2
25                just going cry sleep watching marley me     2
26                                      im sad miss lilly     2
27                   ooooh lol leslie ok i leslie get mad     2
28      meh almost lover exception track gets depresse...     2
29                        hacked account aim make new one     2
...                                                   ...   ...
799969    aww shoot wonder tied knot ryan o neal died sad     2
799970                  ugh i really want go school today     2
799971                                  tell pray problem     2
799972  got checking week ago luckily automatically tr...     2
799973                            rip farrah i hope peace     2
799974                                    rip jill monroe     2
799975                                        doesnt know     2
799976                            said goodbye sam rachel     2
799977                 good miley still awake te midnight     2
799978  big lump throat reading farrah fawcett passing...     2
799979  i get pressure behind left eye sometimes hows ...     2
799980                                        nothing ugh     2
799981                                 i sad i leaving fl     2
799982  hmm sound anywhere remotely close california t...     2
799983  wtching show wa topic farrah still alive i wen...     2
799984                             ugh pics r bog twitter     2
799985      i feel dumb host smart site stuff i know much     2
799986  r i p farrah god bless my prayers love go her ...     2
799987                     farrah fawcett passed away sad     2
799988  just payed way overdue zta dues goodbye that g...     2
799989  i think mind like always ring i taking leak je...     2
799990        banana playing later but shell playing caro     2
799991                                         read tweet     2
799992                                            my life     2
799993  tried get mutant fawkes follow lonely without ...     2
799994             sick spending day laying bed listening     2
799995                                              gmail     2
799996                           rest peace farrah so sad     2
799997     sounds like rival flagging ads not much though     2
799998  resit exams summer wishes worked harder first ...     2

[799999 rows x 2 columns]

In [92]:
df.to_csv('cleanPosData.csv')